# Minimal nixpacks.toml - just fix the npm install
[phases.install]
cmds = ["npm install --legacy-peer-deps --no-audit --no-fund"]

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
